# Generated by Django 2.2.4 on 2019-08-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0006_auto_20190805_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
    ]
