# Generated by Django 2.2.4 on 2019-08-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0008_auto_20190805_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='users_reaction',
        ),
    ]
