# Generated by Django 2.2.4 on 2019-08-07 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soc_net', '0010_auto_20190806_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
